### ISSUE TITLE
FEATURE: Exécution des 'like' en //

### ISSUE THREAD

**Issue by zuzu59** [epfl-dojo/dojo-like-script#20]
Si on met le 'curl' qui fait le 'like' dans un script bash externe au run.sh, on pourrait alors le lancer en // avec un '&'.

Ce qui permettrait GRANDEMENT d'accélérer les grandes listes de 'like' !

**Comment by ponsfrilus** [comment]
See https://stackoverflow.com/a/3096581/960623
